name: Descriptografar arquivo

on:
  workflow_dispatch:
  
jobs:
  decrypt_file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      

    
    - name: Install OpenSSL
      run: sudo apt-get install openssl
      

    
    - name: Descriptografar terraform.tfstate
      if: steps.check_tfstate.outputs.tfstate_exists == 'true'
      run: openssl aes-256-cbc -d -in terraform.tfstate -out terraform.tfstate.decrypted -k ${{ secrets.TERRAFORM_TFSTATE_PASSWORD }}
    - name: Criar terraform.tfstate se não existir
      if: steps.check_tfstate.outputs.tfstate_exists != 'true'
      run: echo "Criando terraform.tfstate..." && touch terraform.tfstate

    - name: Listar arquivos no diretório
      run: ls -l

    - name: Commit e enviar alterações de volta para o repositório
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Adicionar arquivos descriptografados"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
